package br.edu.ifce.mflj.museu.Sino;


/**
* br/edu/ifce/mflj/museu/Sino/ISino.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Tuesday, May 3, 2016 7:20:45 AM BRT
*/

public interface ISino extends ISinoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ISino
