package br.edu.ifce.mflj.museu.Sino;


/**
* br/edu/ifce/mflj/museu/Sino/ISinoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Tuesday, May 3, 2016 7:20:45 AM BRT
*/

public interface ISinoOperations 
{
  void noite (boolean noite);
  boolean entradaDeCliente ();
  void saidaDeCliente ();
} // interface ISinoOperations
