package br.edu.ifce.mflj.museu.Sino;


/**
* br/edu/ifce/mflj/museu/Sino/ISinoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Tuesday, May 3, 2016 7:20:45 AM BRT
*/

abstract public class ISinoHelper
{
  private static String  _id = "IDL:br/edu/ifce/mflj/museu/Sino/ISino:1.0";

  public static void insert (org.omg.CORBA.Any a, br.edu.ifce.mflj.museu.Sino.ISino that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.edu.ifce.mflj.museu.Sino.ISino extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.edu.ifce.mflj.museu.Sino.ISinoHelper.id (), "ISino");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.edu.ifce.mflj.museu.Sino.ISino read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ISinoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.edu.ifce.mflj.museu.Sino.ISino value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.edu.ifce.mflj.museu.Sino.ISino narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.edu.ifce.mflj.museu.Sino.ISino)
      return (br.edu.ifce.mflj.museu.Sino.ISino)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.edu.ifce.mflj.museu.Sino._ISinoStub stub = new br.edu.ifce.mflj.museu.Sino._ISinoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.edu.ifce.mflj.museu.Sino.ISino unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.edu.ifce.mflj.museu.Sino.ISino)
      return (br.edu.ifce.mflj.museu.Sino.ISino)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.edu.ifce.mflj.museu.Sino._ISinoStub stub = new br.edu.ifce.mflj.museu.Sino._ISinoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
