package br.com.ifce.mflj.estacao.sensor.cromometro;


/**
* br/com/ifce/mflj/estacao/sensor/cromometro/ICromometroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cromometro.idl
* Quarta-feira, 8 de Abril de 2015 08h44min37s BRT
*/

abstract public class ICromometroHelper
{
  private static String  _id = "IDL:br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.ifce.mflj.estacao.sensor.cromometro.ICromometroHelper.id (), "ICromometro");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ICromometroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro)
      return (br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.ifce.mflj.estacao.sensor.cromometro._ICromometroStub stub = new br.com.ifce.mflj.estacao.sensor.cromometro._ICromometroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro)
      return (br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.ifce.mflj.estacao.sensor.cromometro._ICromometroStub stub = new br.com.ifce.mflj.estacao.sensor.cromometro._ICromometroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
