package br.com.ifce.mflj.estacao.sensor.cromometro;

/**
* br/com/ifce/mflj/estacao/sensor/cromometro/ICromometroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cromometro.idl
* Quarta-feira, 8 de Abril de 2015 08h44min37s BRT
*/

public final class ICromometroHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro value = null;

  public ICromometroHolder ()
  {
  }

  public ICromometroHolder (br.com.ifce.mflj.estacao.sensor.cromometro.ICromometro initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.ifce.mflj.estacao.sensor.cromometro.ICromometroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ifce.mflj.estacao.sensor.cromometro.ICromometroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ifce.mflj.estacao.sensor.cromometro.ICromometroHelper.type ();
  }

}
