package br.com.ifce.mflj.estacao.sensor.cromometro;


/**
* br/com/ifce/mflj/estacao/sensor/cromometro/ICromometroPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cromometro.idl
* Quarta-feira, 8 de Abril de 2015 08h44min37s BRT
*/

public abstract class ICromometroPOA extends org.omg.PortableServer.Servant
 implements br.com.ifce.mflj.estacao.sensor.cromometro.ICromometroOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ligado", new java.lang.Integer (0));
    _methods.put ("obterLeitura", new java.lang.Integer (1));
    _methods.put ("obterIdentificador", new java.lang.Integer (2));
    _methods.put ("configurarLeitura", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro/ligado
       {
         boolean $result = false;
         $result = this.ligado ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro/obterLeitura
       {
         String $result = null;
         $result = this.obterLeitura ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro/obterIdentificador
       {
         String $result = null;
         $result = this.obterIdentificador ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 3:  // br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro/configurarLeitura
       {
         String leitura = in.read_wstring ();
         this.configurarLeitura (leitura);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICromometro _this() 
  {
    return ICromometroHelper.narrow(
    super._this_object());
  }

  public ICromometro _this(org.omg.CORBA.ORB orb) 
  {
    return ICromometroHelper.narrow(
    super._this_object(orb));
  }


} // class ICromometroPOA
