package br.com.ifce.mflj.estacao.sensor.cromometro;


/**
* br/com/ifce/mflj/estacao/sensor/cromometro/ICromometro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cromometro.idl
* Quarta-feira, 8 de Abril de 2015 08h44min38s BRT
*/

public interface ICromometro extends ICromometroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICromometro
