package br.com.ifce.mflj.estacao;


/**
* br/com/ifce/mflj/estacao/_IServidorCentralStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacaoCentral.idl
* Quarta-feira, 8 de Abril de 2015 08h44min42s BRT
*/

public class _IServidorCentralStub extends org.omg.CORBA.portable.ObjectImpl implements br.com.ifce.mflj.estacao.IServidorCentral
{

  public void informarSensorLigado (String nomeSensor, boolean ligado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("informarSensorLigado", true);
                $out.write_wstring (nomeSensor);
                $out.write_boolean (ligado);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                informarSensorLigado (nomeSensor, ligado        );
            } finally {
                _releaseReply ($in);
            }
  } // informarSensorLigado

  public void informarLeitura (String nomeSensor, String leitura)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("informarLeitura", true);
                $out.write_wstring (nomeSensor);
                $out.write_wstring (leitura);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                informarLeitura (nomeSensor, leitura        );
            } finally {
                _releaseReply ($in);
            }
  } // informarLeitura

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/ifce/mflj/estacao/IServidorCentral:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IServidorCentralStub
