package br.com.ifce.mflj.estacao;


/**
* br/com/ifce/mflj/estacao/IServidorCentralPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacaoCentral.idl
* Quarta-feira, 8 de Abril de 2015 08h44min42s BRT
*/

public abstract class IServidorCentralPOA extends org.omg.PortableServer.Servant
 implements br.com.ifce.mflj.estacao.IServidorCentralOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("informarSensorLigado", new java.lang.Integer (0));
    _methods.put ("informarLeitura", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/com/ifce/mflj/estacao/IServidorCentral/informarSensorLigado
       {
         String nomeSensor = in.read_wstring ();
         boolean ligado = in.read_boolean ();
         this.informarSensorLigado (nomeSensor, ligado);
         out = $rh.createReply();
         break;
       }

       case 1:  // br/com/ifce/mflj/estacao/IServidorCentral/informarLeitura
       {
         String nomeSensor = in.read_wstring ();
         String leitura = in.read_wstring ();
         this.informarLeitura (nomeSensor, leitura);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/ifce/mflj/estacao/IServidorCentral:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IServidorCentral _this() 
  {
    return IServidorCentralHelper.narrow(
    super._this_object());
  }

  public IServidorCentral _this(org.omg.CORBA.ORB orb) 
  {
    return IServidorCentralHelper.narrow(
    super._this_object(orb));
  }


} // class IServidorCentralPOA
