package br.com.ifce.mflj.estacao;


/**
* br/com/ifce/mflj/estacao/IServidorCentral.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacaoCentral.idl
* Quarta-feira, 8 de Abril de 2015 08h44min42s BRT
*/

public interface IServidorCentral extends IServidorCentralOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IServidorCentral
