package br.com.ifce.mflj.estacao;

/**
* br/com/ifce/mflj/estacao/IServidorCentralHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacaoCentral.idl
* Quarta-feira, 8 de Abril de 2015 08h44min42s BRT
*/

public final class IServidorCentralHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ifce.mflj.estacao.IServidorCentral value = null;

  public IServidorCentralHolder ()
  {
  }

  public IServidorCentralHolder (br.com.ifce.mflj.estacao.IServidorCentral initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.ifce.mflj.estacao.IServidorCentralHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ifce.mflj.estacao.IServidorCentralHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ifce.mflj.estacao.IServidorCentralHelper.type ();
  }

}
