package br.com.ifce.mflj.estacao;


/**
* br/com/ifce/mflj/estacao/IServidorCentralOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EstacaoCentral.idl
* Quarta-feira, 8 de Abril de 2015 08h44min42s BRT
*/

public interface IServidorCentralOperations 
{
  void informarSensorLigado (String nomeSensor, boolean ligado);
  void informarLeitura (String nomeSensor, String leitura);
} // interface IServidorCentralOperations
